export const AWARDS_LIST = [
  { id: "CIB", name: "Combat Infantryman Badge", category: "combat_award" },
  { id: "CAB", name: "Combat Action Badge", category: "combat_award" },
  { id: "CMB", name: "Combat Medical Badge", category: "combat_award" },
  { id: "CAR", name: "Combat Action Ribbon", category: "combat_award" },
  { id: "AFCAM", name: "Air Force Combat Action Medal", category: "combat_award" },
  { id: "BSM_V", name: "Bronze Star Medal with V", category: "valor_award" },
  { id: "ARCOM_V", name: "Army Commendation Medal with V", category: "valor_award" },
  { id: "NAVCOM_V", name: "Navy/USMC Commendation Medal with V", category: "valor_award" },
  { id: "AFCOM_V", name: "Air Force Commendation Medal with V", category: "valor_award" },
  { id: "AM_V", name: "Air Medal with V", category: "valor_award" },
  { id: "PH", name: "Purple Heart", category: "medical_related_award" },

  { id: "ICM", name: "Iraq Campaign Medal", category: "campaign_medal" },
  { id: "ACM", name: "Afghanistan Campaign Medal", category: "campaign_medal" },
  { id: "GWOTEM", name: "Global War on Terrorism Expeditionary Medal", category: "campaign_medal" },
  { id: "SASM", name: "Southwest Asia Service Medal", category: "campaign_medal" },
  { id: "KLM_SA", name: "Kuwait Liberation Medal (Saudi Arabia)", category: "campaign_medal" },
  { id: "KLM_KU", name: "Kuwait Liberation Medal (Kuwait)", category: "campaign_medal" },
  { id: "VSM", name: "Vietnam Service Medal", category: "campaign_medal" },
  { id: "AFEM", name: "Armed Forces Expeditionary Medal", category: "campaign_medal" },
  { id: "KCM", name: "Kosovo Campaign Medal", category: "campaign_medal" },
  { id: "IRCM", name: "Inherent Resolve Campaign Medal", category: "campaign_medal" },
  { id: "EFCM", name: "Enduring Freedom Campaign Medal", category: "campaign_medal" },

  { id: "PARACHUTIST_BADGE", name: "Parachutist Badge", category: "hazardous_duty_badge" },
  { id: "AIR_ASSAULT_BADGE", name: "Air Assault Badge", category: "hazardous_duty_badge" },
  { id: "EOD_BADGE", name: "Explosive Ordnance Disposal Badge", category: "hazardous_duty_badge" },
  { id: "DIVER_BADGE", name: "Diver Badge", category: "hazardous_duty_badge" },
  { id: "FLIGHT_CREW_WINGS", name: "Flight Crew Wings", category: "hazardous_duty_badge" },
  { id: "SPECIAL_FORCES_TAB", name: "Special Forces Tab", category: "hazardous_duty_badge" },
  { id: "RANGER_TAB", name: "Ranger Tab", category: "hazardous_duty_badge" },
  { id: "SAPPER_TAB", name: "Sapper Tab", category: "hazardous_duty_badge" },
  { id: "PATHFINDER_BADGE", name: "Pathfinder Badge", category: "hazardous_duty_badge" },
  { id: "AVIATION_BADGES", name: "Aviation Badges (Wings)", category: "hazardous_duty_badge" },

  { id: "AFSM", name: "Armed Forces Service Medal", category: "service_medal" },
  { id: "HSM", name: "Humanitarian Service Medal", category: "service_medal" },
  { id: "OSR", name: "Overseas Service Ribbon", category: "service_medal" },
  { id: "SSDR", name: "Sea Service Deployment Ribbon", category: "service_medal" },
  { id: "NATO_MEDAL", name: "NATO Medal", category: "service_medal" },

  { id: "AM", name: "Air Medal", category: "medical_related_award" },
  { id: "DFC", name: "Distinguished Flying Cross", category: "medical_related_award" },
  { id: "WIA", name: "Wounded in Action", category: "medical_related_award" },

  { id: "POWM", name: "Prisoner of War Medal", category: "high_honor_award" },
  { id: "MOH", name: "Medal of Honor", category: "high_honor_award" },
  { id: "SILVER_STAR", name: "Silver Star", category: "high_honor_award" },
  { id: "DSC", name: "Distinguished Service Cross", category: "high_honor_award" },
  { id: "NAVY_CROSS", name: "Navy Cross", category: "high_honor_award" },
  { id: "AIR_FORCE_CROSS", name: "Air Force Cross", category: "high_honor_award" },
  { id: "BSM", name: "Bronze Star Medal", category: "high_honor_award" },

  { id: "PUC", name: "Presidential Unit Citation", category: "unit_award" },
  { id: "JMUA", name: "Joint Meritorious Unit Award", category: "unit_award" },
  { id: "NUC", name: "Navy Unit Commendation", category: "unit_award" },
  { id: "VUA", name: "Army Valorous Unit Award", category: "unit_award" },
  { id: "MUC", name: "Meritorious Unit Commendation", category: "unit_award" },
  { id: "AFOUA_V", name: "Air Force Outstanding Unit Award (V)", category: "unit_award" },
  { id: "CGUC", name: "Coast Guard Unit Commendation", category: "unit_award" },

  { id: "NDOSM", name: "Nuclear Deterrence Operations Service Medal", category: "rare_award" },
  { id: "ARCTIC_SERVICE_RIBBON", name: "Arctic Service Ribbon", category: "rare_award" },
  { id: "ANTARCTICA_SERVICE_MEDAL", name: "Antarctica Service Medal", category: "rare_award" },
  { id: "NWPB", name: "Nuclear Weapons Personnel Badge", category: "rare_award" },
  { id: "RWB", name: "Radiation Worker Badge", category: "rare_award" }
];

